version: "3.9"

services:
  fastapi:
    build:
      context: .
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - backend
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - backend
    depends_on:
      - fastapi

networks:
  backend:

volumes:
  grafana-storage: